import 'package:dishboard_fruits_app/core/helper/on_generate_function.dart';
import 'package:dishboard_fruits_app/core/services/custom_bloc_observer.dart';
import 'package:dishboard_fruits_app/core/services/get_it.dart';
import 'package:dishboard_fruits_app/features/dishboard/presentation/views/dishboard_view.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // generated by FlutterFire CLI

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase first
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  // Initialize Supabase
  await Supabase.initialize(
    url: 'https://clsszgyzhswrschlsumw.supabase.co',
    anonKey:
        'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNsc3N6Z3l6aHN3cnNjaGxzdW13Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1NjczNDIsImV4cCI6MjA3NDE0MzM0Mn0.DojIzfgCi4YRx1o3zaLASG2cDtX-wFAQwo9Q_dXEiQA',
  );

  // Setup dependency injection AFTER Firebase is ready
  setupGetIt();

  Bloc.observer = CustomBlocObserver();

  runApp(const MainApp());
}

class MainApp extends StatelessWidget {
  const MainApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      onGenerateRoute: onGenerateRoute,
      initialRoute: DishboardView.routeName,
      debugShowCheckedModeBanner: false,
    );
  }
}
